"""baseline

revision: c6ba24c59cdd
revises: 
created: 2026-09-22 18:18:49.643993
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c6ba24c59cdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('target_currency', sa.String(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'uuid'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_rates', schema='public')
    # ### end Alembic commands ###
